name: Generate Snake

on:
  schedule: # Corre cada 24 horas
    - cron: "0 */24 * * *"
  workflow_dispatch: # Permite correr manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 👈 muy importante
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: sergio001g
          outputs: dist/snake.svg

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
